version: '3.8'

services:
  maven:
    image: maven:3.8.6-openjdk-11-slim
    container_name: maven_build
    working_dir: /app
    command: mvn clean package

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: almacen_producto_app
    depends_on:
      - maven

    ports:
      - "8080:8080"
    volumes:
      - target:/app/target
    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  target: